import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/ui/header";
import { AuthProvider } from "@/providers/auth";
import Footer from "@/components/ui/footer";
import CartProvider from "@/providers/cart";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="flex h-full flex-col">
          <AuthProvider>
            <CartProvider>
<<<<<<< HEAD
              <Header />
              <div className="flex-1">{children}</div>
              <Footer />
=======
            <Header />
            <div className="flex-1">{children}</div>
            <Footer />
>>>>>>> b4ddfee108e55df9249787003099452dc1e21dfb
            </CartProvider>
          </AuthProvider>
        </div>
      </body>
    </html>
  );
}
